version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - APP_ENVIRONMENT=development
      - APP_PROJECT_NAME=Investment Tracker API
      - APP_API_V1_PREFIX=/api/v1
    networks:
      - appnet
  frontend:
    build: ./frontend
    command: ["npm", "run", "dev", "--", "--host"]
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
