version: "3.9"

# Load environment variables from prod.env file
# You can override these by setting environment variables directly
# or by modifying the prod.env file

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"  # Expose backend API on port 8000
    volumes:
      - ./backend/portfolio.db:/app/portfolio.db
    env_file:
      - prod.env
    environment:
      - APP_ENVIRONMENT=production
      - APP_PROJECT_NAME=Investment Tracker API
      - APP_API_V1_PREFIX=/api/v1
      - DATABASE_URL=sqlite:///app/portfolio.db
    networks:
      - appnet
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api/v1}
    ports:
      - "8080:80"  # Expose frontend on port 8080
    depends_on:
      - backend
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge

volumes:
  npm_data:
  npm_letsencrypt:
