version: "3.9"
services:
  backend:
    build: ./backend
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/portfolio.db:/app/app/portfolio.db
    environment:
      - APP_ENVIRONMENT=development
      - APP_PROJECT_NAME=Investment Tracker API
      - APP_API_V1_PREFIX=/api/v1
      - DATABASE_URL=sqlite:///app/portfolio.db
    networks:
      - appnet
  frontend:
    build: ./frontend
    command: ["npm", "run", "dev", "--", "--host"]
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tsconfig.app.json:/app/tsconfig.app.json
      - ./frontend/tsconfig.node.json:/app/tsconfig.node.json
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - appnet
networks:
  appnet:
    driver: bridge

volumes:
  frontend_node_modules:
