"""add_realized_pl_tracking

Revision ID: 3e531db625b0
Revises: f7b8c2d1a9e3
Create Date: 2025-09-18 22:43:46.692921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e531db625b0'
down_revision: Union[str, None] = 'f7b8c2d1a9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_company_ticker'), 'company', ['ticker'], unique=True)
    op.create_index(op.f('ix_period_end_date'), 'period', ['end_date'], unique=False)
    op.create_index(op.f('ix_period_label'), 'period', ['label'], unique=True)
    op.create_index(op.f('ix_period_period_type'), 'period', ['period_type'], unique=False)
    op.drop_index('ix_statement_statement_type', table_name='statement')
    op.create_index(op.f('ix_statement_statement_type'), 'statement', ['statement_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statement_statement_type'), table_name='statement')
    op.create_index('ix_statement_statement_type', 'statement', ['statement_type'], unique=False)
    op.drop_index(op.f('ix_period_period_type'), table_name='period')
    op.drop_index(op.f('ix_period_label'), table_name='period')
    op.drop_index(op.f('ix_period_end_date'), table_name='period')
    op.drop_index(op.f('ix_company_ticker'), table_name='company')
    # ### end Alembic commands ###
