"""add_seed_sector_level_1_2

Revision ID: 4558b47687d2
Revises: 3e531db625b0
Create Date: 2025-09-18 22:45:15.844849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4558b47687d2'
down_revision: Union[str, None] = '3e531db625b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Insert Level 1 and Level 2 sectors
    sector_table = sa.table('sector',
        sa.column('id', sa.Integer),
        sa.column('level', sa.Integer),
        sa.column('name', sa.String)
    )
    
    op.bulk_insert(sector_table, [
        # Level 1 sectors
        {'id': 1, 'level': 1, 'name': 'Dầu khí'},
        {'id': 1000, 'level': 1, 'name': 'Nguyên vật liệu'},
        {'id': 2000, 'level': 1, 'name': 'Công nghiệp'},
        {'id': 3000, 'level': 1, 'name': 'Hàng Tiêu dùng'},
        {'id': 4000, 'level': 1, 'name': 'Dược phẩm và Y tế'},
        {'id': 5000, 'level': 1, 'name': 'Dịch vụ Tiêu dùng'},
        {'id': 6000, 'level': 1, 'name': 'Viễn thông'},
        {'id': 7000, 'level': 1, 'name': 'Tiện ích Cộng đồng'},
        {'id': 8000, 'level': 1, 'name': 'Tài chính'},
        {'id': 9000, 'level': 1, 'name': 'Công nghệ Thông tin'},
        
        # Level 2 sectors
        {'id': 500, 'level': 2, 'name': 'Dầu khí'},
        {'id': 1300, 'level': 2, 'name': 'Hóa chất'},
        {'id': 1700, 'level': 2, 'name': 'Tài nguyên Cơ bản'},
        {'id': 2300, 'level': 2, 'name': 'Xây dựng và Vật liệu'},
        {'id': 2700, 'level': 2, 'name': 'Hàng & Dịch vụ Công nghiệp'},
        {'id': 3300, 'level': 2, 'name': 'Ô tô và phụ tùng'},
        {'id': 3500, 'level': 2, 'name': 'Thực phẩm và đồ uống'},
        {'id': 3700, 'level': 2, 'name': 'Hàng cá nhân & Gia dụng'},
        {'id': 4500, 'level': 2, 'name': 'Y tế'},
        {'id': 5300, 'level': 2, 'name': 'Bán lẻ'},
        {'id': 5500, 'level': 2, 'name': 'Truyền thông'},
        {'id': 5700, 'level': 2, 'name': 'Du lịch và Giải trí'},
        {'id': 6500, 'level': 2, 'name': 'Viễn thông'},
        {'id': 7500, 'level': 2, 'name': 'Điện, nước & xăng dầu khí đốt'},
        {'id': 8300, 'level': 2, 'name': 'Ngân hàng'},
        {'id': 8500, 'level': 2, 'name': 'Bảo hiểm'},
        {'id': 8600, 'level': 2, 'name': 'Bất động sản'},
        {'id': 8700, 'level': 2, 'name': 'Dịch vụ tài chính'},
        {'id': 8900, 'level': 2, 'name': 'Đầu tư chứng khoán/phi chứng khoán'},
        {'id': 9500, 'level': 2, 'name': 'Công nghệ Thông tin'},
    ])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove Level 2 sectors first (child records)
    op.execute("DELETE FROM sector WHERE level = 2 AND id IN (500, 1300, 1700, 2300, 2700, 3300, 3500, 3700, 4500, 5300, 5500, 5700, 6500, 7500, 8300, 8500, 8600, 8700, 8900, 9500)")
    
    # Remove Level 1 sectors (parent records)
    op.execute("DELETE FROM sector WHERE level = 1 AND id IN (1, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000)")
    
    # ### end Alembic commands ###
