"""Initial migration

Revision ID: ec6af361d293
Revises: 
Create Date: 2025-08-22 16:05:34.536804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6af361d293'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_amounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=6), nullable=False),
    sa.Column('purchase_price', sa.DECIMAL(precision=15, scale=6), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('smg', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('dif', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('dif_w', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('dif_m', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('dif_3m', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('vonhoa_d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('eps_d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('pe_d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('pb_d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('roa_ttm', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('roe_ttm', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('lnst_yoy_ttm', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('doanhthuthuan_ttm', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('lnst_ttm', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('ocf_ttm', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('lnst_yoy_q', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('novay_q', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('tonkho_q', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('phaithu_q', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('tts_q', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('vcsh_q', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', 'level')
    )
    op.create_table('stock_symbol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id_sector_level_3', sa.Integer(), nullable=True),
    sa.Column('id_sector_level_4', sa.Integer(), nullable=True),
    sa.Column('vonhoa_d', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.Enum('buy', 'sell'), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=15, scale=6), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=15, scale=6), nullable=False),
    sa.Column('close_price', sa.DECIMAL(precision=15, scale=6), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('fees', sa.DECIMAL(precision=10, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('stock_symbol')
    op.drop_table('sector')
    op.drop_table('positions')
    op.drop_table('investment_amounts')
    # ### end Alembic commands ###
